# Generated by Django 5.0.14 on 2025-11-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Finance Sector',
                'verbose_name_plural': 'Finance Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinanceOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID from Tiny ERP', max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='finance.financesector')),
            ],
            options={
                'verbose_name': 'Finance Outflow (Tiny ERP)',
                'verbose_name_plural': 'Finance Outflows (Tiny ERP)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID from Tiny ERP', max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows', to='finance.financesector')),
            ],
            options={
                'verbose_name': 'Finance Inflow (Tiny ERP)',
                'verbose_name_plural': 'Finance Inflows (Tiny ERP)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_date', models.DateField()),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, help_text='Confidence level (0-100%)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Calculation notes or assumptions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_expenses', to='finance.financesector')),
            ],
            options={
                'verbose_name': 'Predicted Expense',
                'verbose_name_plural': 'Predicted Expenses',
                'ordering': ['-predicted_date', '-predicted_amount'],
            },
        ),
    ]
