# Generated by Django 5.0.14 on 2025-11-19 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('launch', 'Collection Launch'), ('promotion', 'Promotion'), ('sale', 'Sale'), ('social_media', 'Social Media'), ('email', 'Email Marketing'), ('influencer', 'Influencer Partnership'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='marketing_campaigns', to='store_collections.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pieces', models.ManyToManyField(blank=True, related_name='marketing_campaigns', to='store_collections.piece')),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('banner', 'Banner'), ('flyer', 'Flyer'), ('brochure', 'Brochure'), ('catalog', 'Catalog'), ('video', 'Video'), ('photo', 'Photo'), ('lookbook', 'Lookbook'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='marketing/materials/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='marketing/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_materials', to='marketing.marketingcampaign')),
                ('collections', models.ManyToManyField(blank=True, related_name='promotional_materials', to='store_collections.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pieces', models.ManyToManyField(blank=True, related_name='promotional_materials', to='store_collections.piece')),
            ],
            options={
                'verbose_name': 'Promotional Material',
                'verbose_name_plural': 'Promotional Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('caption', models.TextField(help_text='Post caption/text')),
                ('hashtags', models.TextField(blank=True, help_text='Hashtags (one per line)')),
                ('image', models.ImageField(blank=True, upload_to='marketing/posts/')),
                ('link_url', models.URLField(blank=True, help_text='Link in bio or post link')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, default=0)),
                ('comments', models.PositiveIntegerField(blank=True, default=0)),
                ('shares', models.PositiveIntegerField(blank=True, default=0)),
                ('views', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='marketing.marketingcampaign')),
                ('collections', models.ManyToManyField(blank=True, related_name='social_posts', to='store_collections.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pieces', models.ManyToManyField(blank=True, related_name='social_posts', to='store_collections.piece')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
