# Generated by Django 5.0.14 on 2025-11-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID from Tiny ERP', max_length=100, unique=True)),
                ('sale_date', models.DateField()),
                ('piece_sku', models.CharField(help_text='SKU of the piece sold', max_length=100)),
                ('piece_name', models.CharField(max_length=200)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_p', models.PositiveIntegerField(default=0, verbose_name='Quantity P')),
                ('quantity_m', models.PositiveIntegerField(default=0, verbose_name='Quantity M')),
                ('quantity_g', models.PositiveIntegerField(default=0, verbose_name='Quantity G')),
                ('quantity_gg', models.PositiveIntegerField(default=0, verbose_name='Quantity GG')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sales Data (Tiny ERP)',
                'verbose_name_plural': 'Sales Data (Tiny ERP)',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('piece', 'Piece Forecast'), ('collection', 'Collection Forecast'), ('fabric', 'Fabric Forecast'), ('overall', 'Overall Forecast')], max_length=20)),
                ('target_name', models.CharField(help_text='Name of piece/collection/fabric being forecasted', max_length=200)),
                ('forecast_date', models.DateField(help_text='Date for which forecast is made')),
                ('predicted_units', models.PositiveIntegerField(default=0)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence_interval_lower', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence_interval_upper', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, help_text='Confidence level (0-100%)', max_digits=5)),
                ('model_used', models.CharField(blank=True, help_text='Statistical model used (e.g., Linear Regression, ARIMA)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the forecast')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Forecast',
                'verbose_name_plural': 'Sales Forecasts',
                'ordering': ['-forecast_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_piece_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pieces_in_collection', models.PositiveIntegerField(default=0)),
                ('best_selling_piece_name', models.CharField(blank=True, max_length=200)),
                ('worst_selling_piece_name', models.CharField(blank=True, max_length=200)),
                ('collection_launch_date', models.DateField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_statistics', to='store_collections.collection')),
            ],
            options={
                'verbose_name': 'Collection Sales Statistics',
                'verbose_name_plural': 'Collection Sales Statistics',
            },
        ),
        migrations.CreateModel(
            name='FabricSalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pieces_using_fabric', models.PositiveIntegerField(default=0)),
                ('total_units_sold', models.PositiveIntegerField(default=0, help_text='Total pieces sold using this fabric')),
                ('total_fabric_consumed_kg', models.DecimalField(decimal_places=2, default=0, help_text='Total fabric consumed in kg', max_digits=10)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_statistics', to='store_collections.fabric')),
            ],
            options={
                'verbose_name': 'Fabric Sales Statistics',
                'verbose_name_plural': 'Fabric Sales Statistics',
            },
        ),
        migrations.CreateModel(
            name='PieceSalesStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sold_p', models.PositiveIntegerField(default=0, verbose_name='Total Sold P')),
                ('total_sold_m', models.PositiveIntegerField(default=0, verbose_name='Total Sold M')),
                ('total_sold_g', models.PositiveIntegerField(default=0, verbose_name='Total Sold G')),
                ('total_sold_gg', models.PositiveIntegerField(default=0, verbose_name='Total Sold GG')),
                ('first_sale_date', models.DateField(blank=True, null=True)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('days_since_launch', models.PositiveIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_statistics', to='store_collections.piece')),
            ],
            options={
                'verbose_name': 'Piece Sales Statistics',
                'verbose_name_plural': 'Piece Sales Statistics',
            },
        ),
    ]
