# Generated by Django 5.0.14 on 2025-11-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('modeling', 'Modeling'), ('pilot_piece', 'Pilot Piece'), ('test_piece', 'Test Piece'), ('production', 'Production'), ('preparation', 'Preparation'), ('transportation', 'Transportation'), ('launch', 'Launch'), ('custom', 'Custom Event')], default='custom', max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('google_event_id', models.CharField(blank=True, help_text='ID from Google Calendar', max_length=200)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Sync with Google Calendar')),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, help_text='Event color (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store_collections.collection')),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
