# Generated by Django 5.0.14 on 2025-11-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypiece',
            name='has_variations',
            field=models.BooleanField(default=False, help_text='True if product has size variations'),
        ),
        migrations.AddField(
            model_name='inventorypiece',
            name='stock_g',
            field=models.IntegerField(default=0, help_text='Stock for size G'),
        ),
        migrations.AddField(
            model_name='inventorypiece',
            name='stock_gg',
            field=models.IntegerField(default=0, help_text='Stock for size GG'),
        ),
        migrations.AddField(
            model_name='inventorypiece',
            name='stock_m',
            field=models.IntegerField(default=0, help_text='Stock for size M'),
        ),
        migrations.AddField(
            model_name='inventorypiece',
            name='stock_p',
            field=models.IntegerField(default=0, help_text='Stock for size P'),
        ),
        migrations.AddField(
            model_name='inventorypiece',
            name='variations_data',
            field=models.JSONField(blank=True, help_text='Raw variations data from Tiny ERP', null=True),
        ),
        migrations.AlterField(
            model_name='inventorypiece',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Total quantity (sum of all sizes)'),
        ),
    ]
