# Generated by Django 5.0.14 on 2025-11-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorypiece_has_variations_inventorypiece_stock_g_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryPiece',
        ),
    ]
