# Generated by Django 5.0.14 on 2025-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDeadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_time', models.PositiveIntegerField(default=0)),
                ('fabric_testing_time', models.PositiveIntegerField(default=0)),
                ('modeling_time', models.PositiveIntegerField(default=0)),
                ('pilot_piece_time', models.PositiveIntegerField(default=0)),
                ('test_piece_for_production', models.PositiveIntegerField(default=0)),
                ('preparation_time', models.PositiveIntegerField(default=0)),
                ('transportation_time', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Deadlines',
                'verbose_name_plural': 'Business Deadlines',
            },
        ),
        migrations.CreateModel(
            name='PieceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Piece Categories',
                'ordering': ['name', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('delivery_time_days', models.PositiveIntegerField(help_text='Delivery time in business days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
