# Generated by Django 5.0.14 on 2025-11-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piececategory',
            name='production_cost_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo médio de produção por peça desta categoria', max_digits=10, verbose_name='Custo de Produção por Peça (R$)'),
        ),
    ]
