# Generated by Django 5.0.14 on 2025-11-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('awaiting_modeler', 'Awaiting Modeler'), ('awaiting_pilot', 'Awaiting Pilot Maker'), ('awaiting_production', 'Awaiting Production'), ('released', 'Released')], default='awaiting_modeler', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('expected_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('modeling_time', models.PositiveIntegerField(help_text='Days for modeling')),
                ('pilot_piece_time', models.PositiveIntegerField(help_text='Days for pilot piece')),
                ('test_piece_time', models.PositiveIntegerField(help_text='Days for test piece')),
                ('production_time', models.PositiveIntegerField(help_text='Days for production')),
                ('preparation_time', models.PositiveIntegerField(help_text='Days for preparation')),
                ('transportation_time', models.PositiveIntegerField(help_text='Days for transportation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('roll_weight_kg', models.DecimalField(decimal_places=2, help_text='Weight of roll in kg', max_digits=10)),
                ('yield_area_per_kg', models.DecimalField(decimal_places=2, help_text='Area per kg (m²/kg)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabrics', to='business_settings.supplier')),
            ],
            options={
                'ordering': ['name', 'color'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_consumption_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fabric Consumption P')),
                ('fabric_consumption_m', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fabric Consumption M')),
                ('fabric_consumption_g', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fabric Consumption G')),
                ('fabric_consumption_gg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fabric Consumption GG')),
                ('initial_quantity_p', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity P')),
                ('initial_quantity_m', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity M')),
                ('initial_quantity_g', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity G')),
                ('initial_quantity_gg', models.PositiveIntegerField(default=0, verbose_name='Initial Quantity GG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessories', models.ManyToManyField(blank=True, related_name='pieces', to='store_collections.accessory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business_settings.piececategory')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='store_collections.collection')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_collections.fabric')),
            ],
            options={
                'ordering': ['collection', 'category'],
            },
        ),
        migrations.CreateModel(
            name='PieceColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store_collections.piece')),
            ],
            options={
                'ordering': ['piece', 'color_name'],
            },
        ),
        migrations.CreateModel(
            name='PieceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pieces/modeling/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store_collections.piece')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
