# Generated by Django 5.0.14 on 2025-11-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('store_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='current_stock_g',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock G'),
        ),
        migrations.AddField(
            model_name='piece',
            name='current_stock_gg',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock GG'),
        ),
        migrations.AddField(
            model_name='piece',
            name='current_stock_m',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock M'),
        ),
        migrations.AddField(
            model_name='piece',
            name='current_stock_p',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Stock P'),
        ),
        migrations.AddField(
            model_name='piece',
            name='stock_last_synced',
            field=models.DateTimeField(blank=True, help_text='Last time stock was synced from Tiny ERP', null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='tiny_erp_piece',
            field=models.ForeignKey(blank=True, help_text='Link to Tiny ERP inventory piece for stock sync', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pieces', to='inventory.inventorypiece'),
        ),
    ]
