# Generated by Django 5.0.14 on 2025-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0002_piece_current_stock_g_piece_current_stock_gg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='name',
            field=models.CharField(blank=True, default='Sem Nome', max_length=200, verbose_name='Nome'),
        ),
    ]
