# Generated by Django 5.0.14 on 2025-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorypiece_has_variations_inventorypiece_stock_g_and_more'),
        ('store_collections', '0003_piece_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='accessories',
            field=models.ManyToManyField(blank=True, related_name='pieces', to='inventory.inventoryaccessory'),
        ),
    ]
