# Generated by Django 5.0.14 on 2025-11-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0004_alter_piece_accessories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
