# Generated by Django 5.0.14 on 2025-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0005_delete_accessory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='tiny_erp_piece',
        ),
        migrations.AddField(
            model_name='piece',
            name='tiny_parent_id',
            field=models.CharField(blank=True, help_text='Parent product ID in Tiny ERP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='tiny_variation_id_g',
            field=models.CharField(blank=True, help_text='Variation ID for size G in Tiny ERP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='tiny_variation_id_gg',
            field=models.CharField(blank=True, help_text='Variation ID for size GG in Tiny ERP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='tiny_variation_id_m',
            field=models.CharField(blank=True, help_text='Variation ID for size M in Tiny ERP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='tiny_variation_id_p',
            field=models.CharField(blank=True, help_text='Variation ID for size P in Tiny ERP', max_length=100, null=True),
        ),
    ]
