# Generated by Django 5.0.14 on 2025-11-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0006_remove_piece_tiny_erp_piece_piece_tiny_parent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2)),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade movimentada')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('inicial', 'Estoque Inicial')], max_length=10)),
                ('stock_after_movement', models.PositiveIntegerField(help_text='Estoque após a movimentação')),
                ('date', models.DateTimeField(help_text='Data e hora da movimentação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='store_collections.piece')),
            ],
            options={
                'verbose_name': 'Histórico de Estoque',
                'verbose_name_plural': 'Históricos de Estoque',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['piece', 'size', 'date'], name='store_colle_piece_i_3d550d_idx'), models.Index(fields=['date'], name='store_colle_date_09e4cd_idx'), models.Index(fields=['movement_type'], name='store_colle_movemen_48a744_idx')],
            },
        ),
    ]
