# Generated by Django 5.0.14 on 2025-11-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0007_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='active_for_replenishment',
            field=models.BooleanField(default=True, verbose_name='Ativa para Reposição'),
        ),
        migrations.AddField(
            model_name='piece',
            name='launch_status',
            field=models.CharField(choices=[('em_lancamento', 'Em Lançamento'), ('lancada', 'Lançada')], default='em_lancamento', max_length=20, verbose_name='Status de Lançamento'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='fabric_consumption_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo de Tecido G (m²)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='fabric_consumption_gg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo de Tecido GG (m²)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='fabric_consumption_m',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo de Tecido M (m²)'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='fabric_consumption_p',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo de Tecido P (m²)'),
        ),
    ]
