# Generated by Django 5.0.14 on 2025-11-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_collections', '0008_piece_active_for_replenishment_piece_launch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='price_per_roll',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço por Rolo (R$)'),
        ),
    ]
